/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useLoader } from "@react-three/fiber";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader";
import { useGLTF, useTexture, Environment } from "@react-three/drei";

const SteelBunny = (props) => {
  const map = useLoader(RGBELoader, "./assets/skylit.hdr");
  const { nodes, materials } = useGLTF("./assets/bunny.gltf");
  return (
    <group {...props} dispose={null} position-y={-0.25}>
      <Environment files="./assets/skylit.hdr" background blur={0.7} />
      <mesh geometry={nodes.bunny.geometry}>
        <meshPhysicalMaterial
          color="orange"
          transmission={0}
          roughness={0}
          metalness={1}
          thickness={0}
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("./assets/bunny.gltf");

export default SteelBunny;
